name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please check if a similar issue already exists.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version
          required: false

  - type: textarea
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📷 Screenshots/Logs
      description: If applicable, add screenshots or logs to help explain your problem
      placeholder: Paste screenshots or logs here...
    validations:
      required: false

  - type: dropdown
    attributes:
      label: 🌍 Environment
      description: What environment are you running?
      options:
        - Development (local)
        - Docker (local)
        - Production (server)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    attributes:
      label: 🖥️ Operating System
      description: What OS are you using?
      placeholder: e.g., Ubuntu 22.04, macOS 13.0, Windows 11
    validations:
      required: true

  - type: input
    attributes:
      label: 🟢 Node.js/Bun Version
      description: What version of Node.js or Bun are you using?
      placeholder: e.g., Bun 1.0.25, Node.js 20.10.0
    validations:
      required: true

  - type: input
    attributes:
      label: 🐳 Docker Version
      description: If using Docker, what version?
      placeholder: e.g., Docker 24.0.7, Docker Compose 2.20.0
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...
    validations:
      required: false