blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/hodwini/typedrasilservice#readme
    about: Read the full documentation and setup guides
    
  - name: 💬 GitHub Discussions
    url: https://github.com/hodwini/typedrasilservice/discussions
    about: Ask questions and discuss ideas with the community
    
  - name: 🔧 API Documentation
    url: http://localhost:3000/docs
    about: Interactive API documentation (when service is running)